stages:
    - build
    - test
    - deploy
variables:
    VERSION: 3.7.2-alpine-1.6.0
    
before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

       
debploy:
    stage: deploy
    
    tags :
        - AVL_1234_Can
    script: 
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - pwd
        - ls -l
        - docker-compose pull
        - docker-compose up -d --force-recreate